# Setup
## Load Packages

In [1]:
library(bayestestR)
library(dplyr)
library(tidyr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

SaSETU already registered with postscriptFont().

SbSETU already registered with postscriptFont().

No regular (non-bold, non-italic) version of ScSETU. Skipping setup for this font.

STIX Two Text already registered with postscriptFont().

System Font already registered with postscriptFont().

Tahoma already registered with postscriptFont().

Times New Roman already registered with postscriptFont().

Trattatello already registered with postscriptFont().

Trebuchet MS already registered with postscriptFont().

Verdana already registered with postscriptFont().

Webdings already registered with postscriptFont().

Wingdings already registered with postscriptFont().

Wingdings 2 already registered with postscriptFont().

Wingdings 3 already registered with postscriptFont().

## Import and Wrangle data

In [2]:
file_paths = list.files(path = ".", pattern="\\.csv$", full.names = T)
file_paths
files = lapply(file_paths, read.csv)
tail(files)

 [1] "./FA1.csv"  "./FA10.csv" "./FA2.csv"  "./FA3.csv"  "./FA4.csv"
 [6] "./FA5.csv"  "./FA6.csv"  "./FA7.csv"  "./FA8.csv"  "./FA9.csv"

[[1]]
                   Date FA. Condition Temperature Colony Rep_1 Rep_2 Rep_3
1   2024-02-12 10:00:00   4       20S          37      1 0.081 0.073 0.078
2   2024-02-12 10:00:00   4       20S          20      1 0.070 0.075 0.093
3   2024-02-12 10:00:00   4       20S          37      2 0.073 0.094 0.089
4   2024-02-12 10:00:00   4       20S          20      2 0.057 0.081 0.063
5   2024-02-12 10:00:00   4       20S          37      3 0.067 0.078 0.075
6   2024-02-12 10:00:00   4       20S          20      3 0.075 0.073 0.071
7   2024-02-12 10:00:00   4       20S          37      4 0.078 0.088 0.076
8   2024-02-12 10:00:00   4       20S          20      4 0.077 0.088 0.062
9   2024-02-12 10:00:00   4       20S          37      5 0.064 0.105 0.062
10  2024-02-12 10:00:00   4       20S          20      5 0.065 0.056 0.057
11  2024-02-12 10:00:00   4       20S          37      6 0.073 0.088 0.074
12  2024-02-12 10:00:00   4       20S          20      6 0.066 0.059 0.084
13  2024-02-12 10:00:00   4       20S          37      7 0.067 0.082 0.080
14  2024-02-12 10:00:00   4       20S          20      7 0.071 0.068 0.070
15  2024-02-12 10:00:00   4       20S          37      8 0.073 0.064 0.104
16  2024-02-12 10:00:00   4       20S          20      8 0.077 0.058 0.071
17  2024-02-12 10:00:00   4       20S          37      9 0.086 0.084 0.079
18  2024-02-12 10:00:00   4       20S          20      9 0.065 0.066 0.063
19  2024-02-12 10:00:00   4       20S          37     10 0.089 0.088 0.092
20  2024-02-12 10:00:00   4       20S          20     10 0.071 0.095 0.062
21  2024-02-12 10:00:00   4       20S          37     11 0.074 0.072 0.072
22  2024-02-12 10:00:00   4       20S          20     11 0.083 0.062 0.073
23  2024-02-12 10:00:00   4       20S          37     12 0.078 0.068 0.078
24  2024-02-12 10:00:00   4       20S          20     12 0.068 0.057 0.078
25  2024-02-12 10:00:00   4       37S          37      1 0.129 0.095 0.132
26  2024-02-12 10:00:00   4       37S          20      1 0.115 0.073 0.134
27  2024-02-12 10:00:00   4       37S          37      2 0.126 0.163 0.122
28  2024-02-12 10:00:00   4       37S          20      2 0.124 0.147 0.122
29  2024-02-12 10:00:00   4       37S          37      3 0.235 0.218 0.195
30  2024-02-12 10:00:00   4       37S          20      3 0.137 0.129 0.103
31  2024-02-12 10:00:00   4       37S          37      4 0.114 0.126 0.118
32  2024-02-12 10:00:00   4       37S          20      4 0.093 0.100 0.148
33  2024-02-12 10:00:00   4       37S          37      5 0.141 0.140 0.135
34  2024-02-12 10:00:00   4       37S          20      5 0.111 0.090 0.117
35  2024-02-12 10:00:00   4       37S          37      6 0.178 0.184 0.206
36  2024-02-12 10:00:00   4       37S          20      6 0.120 0.152 0.138
37  2024-02-12 10:00:00   4       37S          37      7 0.150 0.181 0.151
38  2024-02-12 10:00:00   4       37S          20      7 0.169 0.197 0.167
39  2024-02-12 10:00:00   4       37S          37      8 0.119 0.077 0.081
40  2024-02-12 10:00:00   4       37S          20      8 0.124 0.118 0.088
41  2024-02-12 10:00:00   4       37S          37      9 0.101 0.084 0.091
42  2024-02-12 10:00:00   4       37S          20      9 0.123 0.120 0.096
43  2024-02-12 10:00:00   4       37S          37     10 0.135 0.137 0.144
44  2024-02-12 10:00:00   4       37S          20     10 0.132 0.114 0.108
45  2024-02-12 10:00:00   4       37S          37     11 0.164 0.139 0.139
46  2024-02-12 10:00:00   4       37S          20     11 0.130 0.153 0.123
47  2024-02-12 10:00:00   4       37S          37     12 0.166 0.113 0.159
48  2024-02-12 10:00:00   4       37S          20     12 0.119 0.129 0.132
49  2024-02-12 10:00:00   4         P          37      1 0.125 0.121 0.076
50  2024-02-12 10:00:00   4         P          20      1 0.111 0.097 0.096
51  2024-02-12 10:00:00   4         P          37      2 0.119 0.172 0.138
52  2024-02-12 10:00:00   4         P          20      2 0.156 0.099 0.173
53  2024-02-12 10:00:00   4         P          37      3 0.118 0.141 0.128
54  2024-02-12 10:00:00   4         P          20      3 0.129 0.108 0.105
55  2024-02-12 10:00:00   4         P          37      4 0.086 0.061 0.066
56  2024-02-12 10:00:00   4         P          20      4 0.082 0.085 0.064
57  2024-02-12 10:00:00   4         P          37      5 0.114 0.061 0.061
58  2024-02-12 10:00:00   4         P          20      5 0.082 0.095 0.084
59  2024-02-12 10:00:00   4         P          37      6 0.120 0.110 0.160
60  2024-02-12 10:00:00   4         P          20      6 0.130 0.141 0.133
61  2024-02-12 10:00:00   4         P          37      7 0.133 0.174 0.133
62  2024-02-12 10:00:00   4         P          20      7 0.135 0.111 0.134
63  2024-02-12 10:00:00   4         P          37      8 0.119 0.094 0.072
64  2024-02-12 10:00:00   4         P          20      8 0.095 0.110 0.123
65  2024-02-12 10:00:00   4         P          37      9 0.125 0.095 0.104
66  2024-02-12 10:00:00   4         P          20      9 0.078 0.073 0.075
67  2024-02-12 10:00:00   4         P          37     10 0.095 0.127 0.122
68  2024-02-12 10:00:00   4         P          20     10 0.123 0.109 0.140
69  2024-02-12 10:00:00   4         P          37     11 0.115 0.121 0.125
70  2024-02-12 10:00:00   4         P          20     11 0.101 0.091 0.149
71  2024-02-12 10:00:00   4         P          37     12 0.214 0.175 0.164
72  2024-02-12 10:00:00   4         P          20     12 0.153 0.160 0.126
73  2024-02-14 18:00:00   4       20S          37      1 0.868 0.993 1.232
74  2024-02-14 18:00:00   4       20S          20      1 1.753 1.796 1.807
75  2024-02-14 18:00:00   4       20S          37      2 1.148 1.022 1.220
76  2024-02-14 18:00:00   4       20S          20      2 1.517 1.651 1.676
77  2024-02-14 18:00:00   4       20S          37      3 1.084 1.358 1.232
78  2024-02-14 18:00:00   4       20S          20      3 1.825 1.626 1.559
79  2024-02-14 18:00:00   4       20S          37      4 1.242 1.088 1.044
80  2024-02-14 18:00:00   4       20S          20      4 1.700 1.580 1.508
81  2024-02-14 18:00:00   4       20S          37      5 1.044 1.279 1.130
82  2024-02-14 18:00:00   4       20S          20      5 1.759 1.652 1.459
83  2024-02-14 18:00:00   4       20S          37      6 1.161 1.004 1.045
84  2024-02-14 18:00:00   4       20S          20      6 1.671 1.699 1.643
85  2024-02-14 18:00:00   4       20S          37      7 1.137 1.140 1.153
86  2024-02-14 18:00:00   4       20S          20      7 1.632 1.819 1.500
87  2024-02-14 18:00:00   4       20S          37      8 0.959 0.934 1.071
88  2024-02-14 18:00:00   4       20S          20      8 1.601 1.555 1.360
89  2024-02-14 18:00:00   4       20S          37      9 1.243 1.268 1.123
90  2024-02-14 18:00:00   4       20S          20      9 1.521 1.383 1.457
91  2024-02-14 18:00:00   4       20S          37     10 1.113 1.216 1.151
92  2024-02-14 18:00:00   4       20S          20     10 1.588 1.453 1.536
93  2024-02-14 18:00:00   4       20S          37     11 1.140 1.029 0.984
94  2024-02-14 18:00:00   4       20S          20     11 1.579 1.637 1.595
95  2024-02-14 18:00:00   4       20S          37     12 1.011 0.983 0.928
96  2024-02-14 18:00:00   4       20S          20     12 1.650 1.489 1.596
97  2024-02-14 18:00:00   4       37S          37      1 0.862 0.638 0.737
98  2024-02-14 18:00:00   4       37S          20      1 0.520 0.400 0.736
99  2024-02-14 18:00:00   4       37S          37      2 0.634 0.821 0.618
100 2024-02-14 18:00:00   4       37S          20      2 0.506 0.561 0.561
101 2024-02-14 18:00:00   4       37S          37      3 1.024 0.938 1.004
102 2024-02-14 18:00:00   4       37S          20      3 0.550 0.600 0.518
103 2024-02-14 18:00:00   4       37S          37      4 0.717 0.735 0.771
104 2024-02-14 18:00:00   4       37S          20      4 0.270 0.348 0.490
105 2024-02-14 18:00:00   4       37S          37      5 0.719 0.784 0.706
106 2024-02-14 18:00:00   4       37S          20      5 0.385 0.428 0.517
107 2024-02-14 18:00:00   4       37S          37      6 0.799 0.822 0.905
108 2024-02-14 18:00:00   4       37S          20      6 0.691 0.672 0.684
109 2024-02-14 18:00:00   4       37S          37      7 0.702 0.899 0.875
110 2024-02-14 18:00:00   4       37S          20      7 0.799 0.813 0.681
111 2024-02-14 18:00:00   4       37S          37      8 0.858 0.635 0.591
112 2024-02-14 18:00:00   4       37S          20      8 0.488 0.485 0.391
113 2024-02-14 18:00:00   4       37S          37      9 0.542 0.477 0.575
114 2024-02-14 18:00:00   4       37S          20      9 0.560 0.524 0.499
115 2024-02-14 18:00:00   4       37S          37     10 0.713 0.866 0.742
116 2024-02-14 18:00:00   4       37S          20     10 0.509 0.606 0.427
117 2024-02-14 18:00:00   4       37S          37     11 0.836 0.760 0.763
118 2024-02-14 18:00:00   4       37S          20     11 0.734 0.594 0.518
119 2024-02-14 18:00:00   4       37S          37     12 0.756 0.739 0.841
120 2024-02-14 18:00:00   4       37S          20     12 0.594 0.832 0.590
121 2024-02-14 18:00:00   4         P          37      1 0.744 0.678 0.438
122 2024-02-14 18:00:00   4         P          20      1 0.465 0.388 0.394
123 2024-02-14 18:00:00   4         P          37      2 0.499 0.677 0.589
124 2024-02-14 18:00:00   4         P          20      2 0.698 0.448 0.817
125 2024-02-14 18:00:00   4         P          37      3 0.359 0.470 0.422
126 2024-02-14 18:00:00   4         P          20      3 0.420 0.290 0.302
127 2024-02-14 18:00:00   4         P          37      4 0.462 0.256 0.374
128 2024-02-14 18:00:00   4         P          20      4 0.274 0.326 0.217
129 2024-02-14 18:00:00   4         P          37      5 0.642 0.304 0.294
130 2024-02-14 18:00:00   4         P          20      5 0.208 0.204 0.194
131 2024-02-14 18:00:00   4         P          37      6 0.466 0.387 0.583
132 2024-02-14 18:00:00   4         P          20      6 0.385 0.543 0.465
133 2024-02-14 18:00:00   4         P          37      7 0.674 0.775 0.603
134 2024-02-14 18:00:00   4         P          20      7 0.529 0.460 0.588
135 2024-02-14 18:00:00   4         P          37      8 0.639 0.469 0.435
136 2024-02-14 18:00:00   4         P          20      8 0.272 0.354 0.374
137 2024-02-14 18:00:00   4         P          37      9 0.547 0.367 0.391
138 2024-02-14 18:00:00   4         P          20      9 0.164 0.153 0.155
139 2024-02-14 18:00:00   4         P          37     10 0.443 0.617 0.566
140 2024-02-14 18:00:00   4         P          20     10 0.508 0.506 0.550
141 2024-02-14 18:00:00   4         P          37     11 0.470 0.479 0.563
142 2024-02-14 18:00:00   4         P          20     11 0.397 0.285 0.475
143 2024-02-14 18:00:00   4         P          37     12 0.649 0.682 0.495
144 2024-02-14 18:00:00   4         P          20     12 0.601 0.608 0.552
145 2024-02-16 10:00:00   4       20S          37      1 0.803 0.848 0.950
146 2024-02-16 10:00:00   4       20S          20      1 1.607 1.530 1.858
147 2024-02-16 10:00:00   4       20S          37      2 0.951 0.831 0.871
148 2024-02-16 10:00:00   4       20S          20      2 1.657 1.588 1.604
149 2024-02-16 10:00:00   4       20S          37      3 0.988 1.093 0.938
150 2024-02-16 10:00:00   4       20S          20      3 1.610 1.693 1.779
151 2024-02-16 10:00:00   4       20S          37      4 1.180 0.872 0.839
152 2024-02-16 10:00:00   4       20S          20      4 1.602 1.637 1.808
153 2024-02-16 10:00:00   4       20S          37      5 1.012 1.046 0.989
154 2024-02-16 10:00:00   4       20S          20      5 1.626 1.740 1.438
155 2024-02-16 10:00:00   4       20S          37      6 0.921 0.907 0.878
156 2024-02-16 10:00:00   4       20S          20      6 1.599 1.519 1.669
157 2024-02-16 10:00:00   4       20S          37      7 0.961 1.011 1.014
158 2024-02-16 10:00:00   4       20S          20      7 1.645 1.724 1.744
159 2024-02-16 10:00:00   4       20S          37      8 0.875 0.856 0.840
160 2024-02-16 10:00:00   4       20S          20      8 1.548 1.605 1.678
161 2024-02-16 10:00:00   4       20S          37      9 1.138 1.203 0.946
162 2024-02-16 10:00:00   4       20S          20      9 1.686 1.607 1.521
163 2024-02-16 10:00:00   4       20S          37     10 0.981 1.016 1.012
164 2024-02-16 10:00:00   4       20S          20     10 1.760 1.583 1.795
165 2024-02-16 10:00:00   4       20S          37     11 0.851 0.927 0.832
166 2024-02-16 10:00:00   4       20S          20     11 1.580 1.504 1.559
167 2024-02-16 10:00:00   4       20S          37     12 0.856 0.819 0.771
168 2024-02-16 10:00:00   4       20S          20     12 1.648 1.623 1.508
169 2024-02-16 10:00:00   4       37S          37      1 0.862 0.629 0.675
170 2024-02-16 10:00:00   4       37S          20      1 1.460 1.379 1.474
171 2024-02-16 10:00:00   4       37S          37      2 0.646 0.783 0.616
172 2024-02-16 10:00:00   4       37S          20      2 1.385 1.767 1.482
173 2024-02-16 10:00:00   4       37S          37      3 0.989 0.922 0.963
174 2024-02-16 10:00:00   4       37S          20      3 1.822 1.422 1.873
175 2024-02-16 10:00:00   4       37S          37      4 0.768 0.743 0.905
176 2024-02-16 10:00:00   4       37S          20      4 1.228 1.397 1.336
177 2024-02-16 10:00:00   4       37S          37      5 0.700 0.751 0.712
178 2024-02-16 10:00:00   4       37S          20      5 1.252 1.496 1.663
179 2024-02-16 10:00:00   4       37S          37      6 0.825 0.820 0.837
180 2024-02-16 10:00:00   4       37S          20      6 1.524 1.901 1.626
181 2024-02-16 10:00:00   4       37S          37      7 0.802 0.826 0.833
182 2024-02-16 10:00:00   4       37S          20      7 1.187 1.480 1.245
183 2024-02-16 10:00:00   4       37S          37      8 0.871 0.845 0.636
184 2024-02-16 10:00:00   4       37S          20      8 1.777 1.773 1.516
185 2024-02-16 10:00:00   4       37S          37      9 0.554 0.472 0.580
186 2024-02-16 10:00:00   4       37S          20      9 1.366 1.619 1.437
187 2024-02-16 10:00:00   4       37S          37     10 0.670 0.861 0.714
188 2024-02-16 10:00:00   4       37S          20     10 1.881 1.628 1.659
189 2024-02-16 10:00:00   4       37S          37     11 0.830 0.768 0.760
190 2024-02-16 10:00:00   4       37S          20     11 1.434 1.563 1.458
191 2024-02-16 10:00:00   4       37S          37     12 0.686 0.715 0.777
192 2024-02-16 10:00:00   4       37S          20     12 1.502 1.411 1.517
193 2024-02-16 10:00:00   4         P          37      1 0.728 0.664 0.451
194 2024-02-16 10:00:00   4         P          20      1 1.623 1.525 1.487
195 2024-02-16 10:00:00   4         P          37      2 0.512 0.652 0.589
196 2024-02-16 10:00:00   4         P          20      2 1.817 1.735 1.791
197 2024-02-16 10:00:00   4         P          37      3 0.728 0.691 0.537
198 2024-02-16 10:00:00   4         P          20      3 1.659 1.439 1.499
199 2024-02-16 10:00:00   4         P          37      4 0.663 0.431 0.620
200 2024-02-16 10:00:00   4         P          20      4 1.374 1.651 1.305
201 2024-02-16 10:00:00   4         P          37      5 0.922 0.617 0.626
202 2024-02-16 10:00:00   4         P          20      5 1.163 1.245 1.144
203 2024-02-16 10:00:00   4         P          37      6 0.536 0.675 0.777
204 2024-02-16 10:00:00   4         P          20      6 1.445 1.366 1.509
205 2024-02-16 10:00:00   4         P          37      7 0.663 0.753 0.602
206 2024-02-16 10:00:00   4         P          20      7 1.677 1.728 1.929
207 2024-02-16 10:00:00   4         P          37      8 0.695 0.554 0.533
208 2024-02-16 10:00:00   4         P          20      8 1.474 1.357 1.400
209 2024-02-16 10:00:00   4         P          37      9 0.709 0.585 0.558
210 2024-02-16 10:00:00   4         P          20      9 0.840 1.091 0.997
211 2024-02-16 10:00:00   4         P          37     10 0.463 0.608 0.553
212 2024-02-16 10:00:00   4         P          20     10 1.974 1.925 2.087
213 2024-02-16 10:00:00   4         P          37     11 0.498 0.550 0.626
214 2024-02-16 10:00:00   4         P          20     11 1.723 0.953 2.185
215 2024-02-16 10:00:00   4         P          37     12 0.811 0.817 0.727
216 2024-02-16 10:00:00   4         P          20     12 1.428 1.499 1.444
217 2024-02-15 18:00:00   4       20S          37      1 1.062 1.053 1.101
218 2024-02-15 18:00:00   4       20S          20      1 1.558 1.605 1.812
219 2024-02-15 18:00:00   4       20S          37      2 1.041 1.058 1.007
220 2024-02-15 18:00:00   4       20S          20      2 1.640 1.727 1.635
221 2024-02-15 18:00:00   4       20S          37      3 1.205 1.246 1.084
222 2024-02-15 18:00:00   4       20S          20      3 1.647 1.702 1.696
223 2024-02-15 18:00:00   4       20S          37      4 1.264 0.980 0.948
224 2024-02-15 18:00:00   4       20S          20      4 1.692 1.644 1.630
225 2024-02-15 18:00:00   4       20S          37      5 1.238 1.179 1.069
226 2024-02-15 18:00:00   4       20S          20      5 1.691 1.724 1.387
227 2024-02-15 18:00:00   4       20S          37      6 1.058 1.153 1.029
228 2024-02-15 18:00:00   4       20S          20      6 1.583 1.470 1.603
229 2024-02-15 18:00:00   4       20S          37      7 1.062 1.224 1.209
230 2024-02-15 18:00:00   4       20S          20      7 1.568 1.754 1.739
231 2024-02-15 18:00:00   4       20S          37      8 1.088 1.017 0.961
232 2024-02-15 18:00:00   4       20S          20      8 1.538 1.715 1.683
233 2024-02-15 18:00:00   4       20S          37      9 1.203 1.282 1.043
234 2024-02-15 18:00:00   4       20S          20      9 1.529 1.552 1.589
235 2024-02-15 18:00:00   4       20S          37     10 1.120 1.118 1.129
236 2024-02-15 18:00:00   4       20S          20     10 1.434 1.513 1.413
237 2024-02-15 18:00:00   4       20S          37     11 0.977 1.045 0.956
238 2024-02-15 18:00:00   4       20S          20     11 1.627 1.595 1.646
239 2024-02-15 18:00:00   4       20S          37     12 1.035 0.925 0.951
240 2024-02-15 18:00:00   4       20S          20     12 1.670 1.592 1.649
241 2024-02-15 18:00:00   4       37S          37      1 0.868 0.642 0.710
242 2024-02-15 18:00:00   4       37S          20      1 1.348 1.363 1.435
243 2024-02-15 18:00:00   4       37S          37      2 0.654 0.817 0.624
244 2024-02-15 18:00:00   4       37S          20      2 1.361 1.452 1.540
245 2024-02-15 18:00:00   4       37S          37      3 1.017 0.945 0.996
246 2024-02-15 18:00:00   4       37S          20      3 1.565 1.569 1.718
247 2024-02-15 18:00:00   4       37S          37      4 0.762 0.754 0.854
248 2024-02-15 18:00:00   4       37S          20      4 1.003 1.025 1.242
249 2024-02-15 18:00:00   4       37S          37      5 0.715 0.780 0.725
250 2024-02-15 18:00:00   4       37S          20      5 1.185 1.343 1.449
251 2024-02-15 18:00:00   4       37S          37      6 0.828 0.838 0.880
252 2024-02-15 18:00:00   4       37S          20      6 1.606 1.692 1.860
253 2024-02-15 18:00:00   4       37S          37      7 0.791 0.872 0.882
254 2024-02-15 18:00:00   4       37S          20      7 1.279 1.524 1.386
255 2024-02-15 18:00:00   4       37S          37      8 0.873 0.765 0.639
256 2024-02-15 18:00:00   4       37S          20      8 1.359 1.335 1.170
257 2024-02-15 18:00:00   4       37S          37      9 0.559 0.487 0.594
258 2024-02-15 18:00:00   4       37S          20      9 1.230 1.408 1.169
259 2024-02-15 18:00:00   4       37S          37     10 0.700 0.887 0.738
260 2024-02-15 18:00:00   4       37S          20     10 1.442 1.481 1.389
261 2024-02-15 18:00:00   4       37S          37     11 0.839 0.768 0.776
262 2024-02-15 18:00:00   4       37S          20     11 1.620 1.660 1.650
263 2024-02-15 18:00:00   4       37S          37     12 0.737 0.729 0.825
264 2024-02-15 18:00:00   4       37S          20     12 1.234 1.404 1.467
265 2024-02-15 18:00:00   4         P          37      1 0.732 0.665 0.448

In [3]:
# Convert the date and time and fix the column names for each of the dataframes
for (x in 1:length(file_paths)) {
    files[[x]]$Date <- as.POSIXct(files[[x]]$Date)
    files[[x]]$Date <- as.numeric(difftime(files[[x]]$Date, min(files[[x]]$Date), units = "hours"))
    names(files[[x]])[names(files[[x]]) == 'FA.'] <- 'FA'
    names(files[[x]])[names(files[[x]]) == 'Date'] <- 'Hours'
}

In [4]:
#combine into one dataframe
data <- do.call("rbind", files) 
head(data)
dim(data)

  Hours FA Condition Temperature Colony Rep_1 Rep_2 Rep_3 Rep_4 Rep_5
1 56    1  A         37          1      1.144 1.087 1.073 1.187 1.107
2 56    1  A         20          1      1.446 1.574 1.379 1.479 1.410
3 56    1  A         37          2      0.730 0.914 0.796 0.832 0.776
4 56    1  A         20          2      1.197 1.190 1.512 1.366 0.872
5 56    1  A         37          3      0.870 0.727 0.699 0.748 0.648
6 56    1  A         20          3      1.298 1.517 1.491 1.473 1.481

[1] 7584   10

In [5]:
# Condense the Reps into one column and combine columns to make it easier to process
temp <- data %>%
            pivot_longer(cols = starts_with("Rep_"), 
                         names_to = "Rep", 
                         names_prefix = "Rep_", 
                         values_to = "OD") %>%
            unite(group, c("FA", "Condition", "Temperature", "Colony", "Rep"))
temp$Area <- 0
head(temp)
dim(temp)

  Hours group      OD    Area
1 56    1_A_37_1_1 1.144 0
2 56    1_A_37_1_2 1.087 0
3 56    1_A_37_1_3 1.073 0
4 56    1_A_37_1_4 1.187 0
5 56    1_A_37_1_5 1.107 0
6 56    1_A_20_1_1 1.446 0

[1] 37920     4

# Calculate AUC
Opted for the cumulative AUC, wherein the area of the current time segment is added to the previous segment area. This method was chosen as the more logical option, compared to calculating the AUC at each timepoint from t0. Both methods have a correlation of 0.99.

In [6]:
groups <- unique(temp$group)
length(groups)

[1] 4080

In [7]:
area_temp <- c()
groups <- unique(temp$group)

for (i in 1:length(groups)){
    #subset the group and put in order
    subset_df <- arrange(temp[temp$group == groups[i],], Hours)
    
    times <- sort(unique(subset_df$Hours))
    previous_section_area <- 0
    for (t in 2:length(times)){
        #subset for the current time and the previous time
        subset_time_df <- subset_df %>% filter(Hours == times[t] | Hours == times[t-1])
        
        #Calculate current section area
        current_section_area <- area_under_curve(subset_time_df$Hours, subset_time_df$OD, method = "spline")
        
        # Add it to the previous section area
        subset_df[subset_df$Hours == times[t], "Area"] <- current_section_area + previous_section_area
        
        # Overwrite the previous section area to the current section area
        previous_section_area <- current_section_area + previous_section_area
    }
    area_temp[[i]] <- data.frame(subset_df)
}

## Clean up

In [8]:
area_df <- do.call("rbind", area_temp) %>% 
            separate(group, c("FA", "Condition", "Temperature", "Colony", "Rep")) %>%
            mutate_at(c("Temperature", "Rep"), factor) %>%
            mutate_at(c("FA", "Colony"), as.numeric)
head(area_df)
dim(area_df)

  Hours FA Condition Temperature Colony Rep OD    Area
1  0    1  A         37          1      1   0.074  0.000
2  8    1  A         37          1      1   0.407  1.924
3 24    1  A         37          1      1   1.296 15.548
4 32    1  A         37          1      1   1.194 25.508
5 48    1  A         37          1      1   1.151 44.268
6 56    1  A         37          1      1   1.144 53.448

[1] 37920     8

In [9]:
#Create copies of the original data for each condition for t0
area_df_A <- area_df[area_df$Condition == "A",]
dim(area_df_A)
area_df_A$Condition <- "37S"
area_df_S <- area_df_A
area_df_S$Condition <- "20S"
temp <- rbind(area_df_A, area_df_S)
area_df_S$Condition <- "P"
temp <- rbind(temp, area_df_S)
area_df_noA <- rbind(temp, area_df[area_df$Condition != "A",])
table(area_df_noA$Condition)

[1] 1200    8

  20S   25S   37S     P
11280  6480 11280 11280

In [10]:
area_df_noA$Hours <- area_df_noA$Hours / 24
names(area_df_noA)[names(area_df_noA) == 'Hours'] <- 'Days'
condition_names <- c("20S" = "20°C Specialist",
                    "37S" = "37°C Specialist",
                    "P" = "Plastic/Fluctuating", 
                    "25S" = "25°C Control")

## Export

In [12]:
write.csv(area_df_noA, "../HE_area_table_additive.csv", row.names = F)