In [2]:
import pandas as pd
from os import listdir
from os.path import isfile, join
import seaborn as sns

In [16]:
def combine_data(file_path, absorbance):
    all_data = []
    counter = 0
    for f in listdir("./"):
        if f.endswith(".csv"):
            data = pd.read_csv(join("./", f))
            # data = data[data["Absorbance"] == absorbance]
            data.loc[data["Temperature"] == 25, "Temperature"] += counter
            counter += 0.1
            all_data.append(data)
                
    all_data = pd.concat(all_data)
    all_data = all_data[all_data.columns[1:]]
    return all_data.reset_index()

In [17]:
all_data = combine_data("./", 680)
all_data.tail()

/var/folders/60/dqd3cz_50xq54gcmcz_k3_800000gn/T/ipykernel_26436/58345787.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[25.1 25.1 25.1 ... 25.1 25.1 25.1]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[data["Temperature"] == 25, "Temperature"] += counter
/var/folders/60/dqd3cz_50xq54gcmcz_k3_800000gn/T/ipykernel_26436/58345787.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[25.2 25.2 25.2 ... 25.2 25.2 25.2]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[data["Temperature"] == 25, "Temperature"] += counter
/var/folders/60/dqd3cz_50xq54gcmcz_k3_800000gn/T/ipykernel_26436/58345787.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[25.3 25.3 25.3 ... 25.3 25.3 25.3]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[data["Temperature"] == 25, "Temperature"] += counter

,index,ID,value,Hours,Absorbance,Temperature,Cell_Line,Replicate,log10_transformed
38011,7915,20230712-9PM_750_30_BMS_3,0.991,58.0,750,30.0,BMS,3,-0.003926
38012,7916,20230712-9PM_750_30_BMS_4,0.902,58.0,750,30.0,BMS,4,-0.044793
38013,7917,20230712-9PM_750_30_BMS_5,0.949,58.0,750,30.0,BMS,5,-0.022734
38014,7918,20230712-9PM_750_30_BMS_6,0.405,58.0,750,30.0,BMS,6,-0.392545
38015,7919,20230712-9PM_750_30_BMS_7,0.813,58.0,750,30.0,BMS,7,-0.089909

In [18]:
#2343 rep 4 at 32°C wasn't filled, so we can remove it from the analysis

all_data.drop(list(all_data[(all_data.Cell_Line == "2342") & (all_data.Replicate == 4) & ((all_data.Temperature == 32) | (all_data.Temperature == 28) |(all_data.Temperature == 25.1))].index), inplace = True)
all_data[(all_data.Cell_Line == "2342") & (all_data.Replicate == 4) & (all_data.Temperature == 32)]
# all_data[(all_data.Cell_Line == "2342") & (all_data.Replicate == 4) & (all_data.Temperature == 20)]

Empty DataFrame
Columns: [index, ID, value, Hours, Absorbance, Temperature, Cell_Line, Replicate, log10_transformed]
Index: []

In [20]:
# Export Data
all_data["ID"] = all_data["Cell_Line"].astype("str") + "_"+ all_data["Temperature"].astype("str") +"_"+ all_data["Replicate"].astype("str") +"_"+ all_data["Absorbance"].astype("str")
data_export_reps = all_data.pivot_table(values='value', index='Hours', columns='ID')

data_export_reps.shape
data_export_reps.to_csv("../Annotating/Raw_Temperature_Screen.csv")

In [46]:
data_export_reps.shape

(46, 2370)